name: Ejecutar script semanalmente

on:
  workflow_dispatch:
  schedule:
    - cron: '* * */7 * *' # Esta línea se configura para ejecutar el script cada viernes a las 13:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Imprimir directorio actual
        run: tree . -L 3
#       - name: Set up workspace
#         run: echo "workspace:${{ github.workspace }}" >> $GITHUB_ENV
      - name: Ejecutar script
        run: python automatizacion.py # Esta línea se configura para ejecutar tu script. Asegúrate de que la ruta sea correcta.
        id: script_result
        continue-on-error: true
        working-directory: ./src
      - name: Imprimir resultado del script
        run: echo "${{ steps.script_result.stdout }}"
