name: Ejecutar script semanalmente

on:
  schedule:
    - cron: '*/5 * * * *' # Esta línea se configura para ejecutar el script cada viernes a las 13:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Ejecutar script
        run: python src/automatizacion.py # Esta línea se configura para ejecutar tu script. Asegúrate de que la ruta sea correcta.
